CREATE TABLE customers(id TEXT PRIMARY KEY,name VARCHAR(100) NOT NULL,email TEXT NOT NULL UNIQUE,phone TEXT,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE products(id TEXT PRIMARY KEY,cat TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',price NUMERIC(12,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0),location TEXT NOT NULL DEFAULT '',rating NUMERIC(3,2) NOT NULL DEFAULT 5,reviews INTEGER NOT NULL DEFAULT 0,sold INTEGER NOT NULL DEFAULT 0,image TEXT,is_custom BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE payment_info(id INTEGER PRIMARY KEY,card_number TEXT NOT NULL,card_holder TEXT NOT NULL,bank TEXT NOT NULL);
CREATE TABLE orders(id TEXT PRIMARY KEY,customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL,customer_name TEXT NOT NULL,customer_phone TEXT NOT NULL,total NUMERIC(12,2) NOT NULL,status TEXT NOT NULL DEFAULT 'tekshirilmoqda',receipt TEXT,paid_to_card TEXT,sold_counted BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE order_pickup_locations(order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,location TEXT);
CREATE TABLE order_items(id BIGSERIAL PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id TEXT NOT NULL,name TEXT NOT NULL,price NUMERIC(12,2) NOT NULL,qty INTEGER NOT NULL CHECK(qty>0),location TEXT);
CREATE INDEX idx_orders_customer ON orders(customer_id);CREATE INDEX idx_orders_status ON orders(status);CREATE INDEX idx_order_items_order ON order_items(order_id);
INSERT INTO payment_info VALUES(1,'8600 1234 5678 9012','VERMONT SHOP','Uzcard / Humo');
INSERT INTO products(id,cat,name,description,price,stock,location,rating,reviews,sold) VALUES
('p1','soat','Nordwerk Chrono','Po‘lat korpus, sapfir shisha.',1890000,18,'Toshkent',4.8,214,0),('p2','soat','Meridian Steel','Klassik minimal siferblat.',1240000,24,'Samarqand',4.6,132,0),('p3','kamar','Toskana Full-Grain','Italyan charmidan klassik kamar.',320000,60,'Toshkent',4.9,401,0),('p4','hamyon','Cardholder Slim','Yupqa RFID himoyali hamyon.',210000,5,'Buxoro',4.7,356,0),('p5','koinok','Aviator Matte','UV400 himoya, titanium ramka.',340000,22,'Namangan',4.7,267,0);
